disabled_rules:
  - trailing_whitespace
  - identifier_name
  - multiple_closures_with_trailing_closure
 
opt_in_rules:
   - multiline_parameters_brackets
   - multiline_arguments_brackets

excluded:
  - Pods

line_length:
  ignores_comments: true
